### ISSUE TITLE
Temporary TODO list

### ISSUE THREAD

**Issue by Bubobubobubobubo** [felixroos/kabelsalat#1]
As discussed, here is a short TODO list in order to expand the capabilities of KabelSalat. My ideas mostly come from toying around with SuperCollider a lot:

**Signals**

- [ ] extension of the `range` method to support different scalings
  - [ ] `linlin`, `linexp`, `explin`, `expexp` with `omin`, `omax`, `tmin` and `tmax` as params.
- [ ] non-linear/non-periodic modulators inspired by SC UGens
  - [ ]  `LFNoise0` (step noise)
  - [ ] `LFNoise1` (linearly interpolated random values)
  - [ ] `LFNoise2` (quadratically interpolated random values)
  - [ ] `LFDNoise3` (polynomially interpolated random values)
- [ ] Useful methods working on any arbitrary signal
  - [ ] `clip` (clipping), `fold` (folding with `min` and `max`), `unipolar`, `bipolar`
  - [ ] `lag` methods for delaying a signal
  - [ ] `slew` (with a units per second parameter)
- [ ] radians and degrees functions for math people 

**Triggers**

- [ ] Optional `gate/trig` argument for ramps/envs/signals
- [ ] Impulsion generators for trigger/gates
  - [ ] Periodic pulses (like `Impulse`)
  - [ ] Aperiodic pulses (like `Dust` or `Dust2`)

**Interface/GUI**

- [ ] `MouseX` and `MouseY` for fun and pedagogy
- [ ] VIM!

**Comment by felixroos** [comment]
rangex: https://felixroos.github.io/kabelsalat/#c2luZShbMSwzXSkucmFuZ2V4KDEwMCwgMmUzKS5zaW5lKCkub3V0KCk=
